# Generated by Django 4.1.9 on 2023-05-05 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc2005', '0003_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tc2005.user',),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='tasks',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='time',
            field=models.IntegerField(default=180, validators=[django.core.validators.MaxValueValidator(180)]),
        ),
    ]
