# Generated by Django 4.1.9 on 2023-05-05 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc2005', '0004_superuser_scoreboard_completed_scoreboard_tasks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboard',
            name='time',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(180)]),
        ),
    ]
